### ISSUE TITLE
How to add an icon or an image to the web push notification

### ISSUE THREAD

**Issue by kopax** [web-push-libs/webpush-java#148]
Hello, I am reading `Notification` class and I can't see where the `icon` or `image` can be set, could you please show us an example? Thanks in advance

Source: https://developer.mozilla.org/en-US/docs/Web/API/Notification/icon

**Comment by martijndwars** [comment]
This library is used on the server to send the push message. Upon creating the push subscription, the browser registers a service worker that can listen to `push` events. It is up to the service worker to create the notification. As such, creating the notification is outside the scope of this library.

**Comment by kopax** [comment]
Yes I figured out all that my self that is why I have closed the issue. Thank you for the reply still. I have implemented my self the same mechanism but for web push token, I got them working in my expo app, do you have an idea why expo does not allow them at that time? Will you add the support later if a day they would support it?

**Comment by martijndwars** [comment]
>  I got them working in my expo app, do you have an idea why expo does not allow them at that time? 

I assume you are referring to [expo.io](https://expo.io/)? I have no experience with Expo, so I cannot really answer this. Are you saying you got it working with Expo? Or does it not work because Expo does not allow push notifications?

iOS does not support the Web Push protocol, so if you are deploying your Expo app as an iOS app, then that likely won't work. You need to use Apple Push Notification Service (APNS) to support iOS. In fact, [Expo has their own Push API](https://docs.expo.io/push-notifications/sending-notifications/) that forwards push messages to either Web Push (Android) or APNS (iOS). Is that what you are looking for?
