### ISSUE TITLE
Chrome notifications not using registrationId anymore?

### ISSUE THREAD

**Issue by yaronshahverdi** [web-push-libs/webpush-java#32]
I noticed in this commit: https://github.com/web-push-libs/webpush-java/commit/64baebcf6bb0d7ce5a6e6d97110095362c72dd94#diff-635c01aada177ec436f99d8e16a73972 that for Chrome notifications, the POST body being sent is no longer the same as it was before, which was: 
`{
    "registration_ids": [...],
    "raw_data": .....
}`

Is this intended behavior? I've read that the entire body might need to be encrypted, which is what it seems like the code is now doing, but it seems a little strange that GcmNotification registrationIds are no longer being used anywhere in making the request (and I'm getting error=MissingRegistration when sending the notifications).

**Comment by martijndwars** [comment]
The Web Push protocol has been going through a lot of changes. For a long time Chrome used a non-standard protocol. The POST body you refer to is part of this non-standard protocol. Since version 52 Chrome is compatible with the standard Web Push protocol, which relies on VAPID for server identification. This is the preferred approach nowadays.

> I've read that the entire body might need to be encrypted

You probably created the subscription (by calling `pushManager.subscribe`) before VAPID was supported. In that case you do not need to (and cannot) use encryption, since this relies on the server identifying itself the moment the subscription is created.

> it seems a little strange that GcmNotification registrationIds are no longer being used anywhere in making the request (and I'm getting error=MissingRegistration when sending the notifications).

Previously the registrationIds were extracted from the endpoint. With the new protocol you can use the endpoint directly, so the registrationIds are still being used in making the request.

> and I'm getting error=MissingRegistration when sending the notifications

I'm not sure why you're getting this error. Managing different versions of subscriptions is a big pain. If possible, I would suggest truncating the old subscriptions and start using new VAPID-based subscriptions. If this is not possible, you might be better of using the old version of this library.

**Comment by yaronshahverdi** [comment]
Ah, that makes sense! I didn't realize the new protocol allows the endpoint to be used directly, so I was still using the old GcmNotification class, which had previously hard-coded the GCM endpoint without the registrationId, which is why I was getting the MissingRegistration error. 

Thanks for the quick and helpful info Martijn!

**Comment by martijndwars** [comment]
You're welcome! Also note that the new protocol is more uniform. Previously you had to create a web app manifest that listed your `gcm_sender_id` that was connected to a Google Developer Project in GCM to get web push working in Chrome. All of this is no longer necessary with VAPID.

@gauntface did a great job documenting this at https://web-push-book.gauntface.com/chapter-06/01-non-standards-browsers/.
