### ISSUE TITLE
key spec not recognised

### ISSUE THREAD

**Issue by trashhead** [web-push-libs/webpush-java#35]
Hi

I'm having trouble getting this to work.
I have generated keys with the help of:
C:\Proj\git\webpush-java>java -jar build/libs/web-push-3.0.0-all.jar generate-key
PublicKey:
BMU04E2PG6WEPFNpNjdm2axI-tPkBwIgEP60WVRy9-fgCKvPC7U1DA02XaPG9-Iwj_l6EnHo9zbW-aNhNO8BLDk=
PrivateKey:
G5yq2I6-xwK2pRizUFznueDbYm-DNgkHfWB4DqqS9Pc=

And in my java code I try to do:
String publicKey = "BMU04E2PG6WEPFNpNjdm2axI-tPkBwIgEP60WVRy9-fgCKvPC7U1DA02XaPG9-Iwj_l6EnHo9zbW-aNhNO8BLDk=";
String privateKey = "G5yq2I6-xwK2pRizUFznueDbYm-DNgkHfWB4DqqS9Pc=";
PushService pushService = new PushService(publicKey, privateKey, "mailto:admin@domain.com");

But I get "key spec not recognised".
What am I doing wrong, is it the subject that is wrong? what should the subject be ?

**Comment by trashhead** [comment]
I found this stackoverflow thread: https://stackoverflow.com/questions/36252742/wildfly-10-bouncycastlecrypto-ecdsa-key-spec-not-recognized. His solution was to add this to jboss-deployment-structure.xml:

```
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.1">
    <deployment>
        <dependencies>
            <module name="org.bouncycastle" />
        </dependencies>
    </deployment>
</jboss-deployment-structure>
```


And it works ! :)

**Comment by martijndwars** [comment]
The problem is that BouncyCastle's JARs are signed, which prevents you from including the contents of the JAR in your project (i.e. you need to put the JAR itself on your classpath, not its contents).

I've had a lot of trouble with this myself, but there is little I can do since the solution depends on the way you package and deploy your application (and thus is different for everybody). Hopefully other JBoss users can use this issue to guide them, thanks!

**Comment by ArraisLF** [comment]
I'm having the same issue using Spring Boot and Maven. I've tried adding the jar to my jre and adding bouncycastle as a provider in java.security but I'm still getting the "key spec not recognized" error. I'm all out of ideas right now. @MartijnDwars Can you share some of your experience on your past troubles with this? Thanks in advance, looking forward to using your lib.

**Comment by martijndwars** [comment]
I just created a fresh Spring Boot + Maven application using [Spring Initializr](https://start.spring.io/) and created a minimal example to send a push notification. You can find the code and usage instructions [here](https://github.com/MartijnDwars/spring-boot-web-push). Does this help?

**Comment by ArraisLF** [comment]
Hey @MartijnDwars thanks for the quick reply. Your code worked just fine out of the box, but I'm not really sure why yours worked with no additional configuration and mine didn't. Right now my code is working after I removed bouncycastle dependencies from maven and downloaded them again, but I'm still absolutely lost as to why I was having that "key spec not recognised" problem. I'll try to reproduce the error and see if I can pin it down more specifically. Thanks again for the great work on this library!

**Comment by martijndwars** [comment]
> Right now my code is working after I removed bouncycastle dependencies from maven and downloaded them again, but I'm still absolutely lost as to why I was having that "key spec not recognised" problem

I guess this depends on how you package your application. Note that the Spring Boot Maven Plugin allows you to nest JARs, which is different from how Maven usually packages dependencies. Specifically, using the Spring Boot Maven Plugin, Maven creates a JAR that contains `bcprov-jdk15on-1.54.jar`, i.e. the BouncyCastle JAR itself (instead of its contents). As outlined in my [previous comment](https://github.com/web-push-libs/webpush-java/issues/35#issuecomment-315111459), this is necessary to avoid breaking the signature on the BouncyCastle JAR. Anyway, I'm glad it works for you now.
