### ISSUE TITLE
Seems like service worker event.data is null if for example the character å is in the payload

### ISSUE THREAD

**Issue by trashhead** [web-push-libs/webpush-java#36]
Don't know if it is the library or the push api or something else. But at least when having the character å in the payload, the data property on the event becomes null. Would assume the same goes for all three umlauts åäö. If I Base64 it before sendoff it works.

**Comment by martijndwars** [comment]
This is probably a bug in this library, as we've seen this problem before (#27). How do you invoke the this library? Are you using [this](https://github.com/web-push-libs/webpush-java/blob/fd1f3911b9d23f331bc45e5b1f0c5b2422475648/src/main/java/nl/martijndwars/webpush/Notification.java#L52) constructor, instead of passing along the raw bytes yourself to [this](https://github.com/web-push-libs/webpush-java/blob/fd1f3911b9d23f331bc45e5b1f0c5b2422475648/src/main/java/nl/martijndwars/webpush/Notification.java#L48) constructor? I suspect that the call `String.getBytes()` is the culprit, as this relies on the platform's (i.e. JVM's) default charset.

**Comment by trashhead** [comment]
Not quite sure I understand you but this is my code:

```java
String publicKey = "<public>";
String privateKey = "<private>";
PushService pushService = new PushService(publicKey, privateKey, "mailto:admin@domain.com");
					
Subscription subscription = new Subscription();
Keys keys = subscription.new Keys();
keys.auth = "<auth>";
keys.p256dh = "<p256>";
subscription.endpoint = "<endpoint>";
subscription.keys = keys;

Notification notification = new Notification(subscription, "åäö"));
HttpResponse response = pushService.send(notification);
```

**Comment by martijndwars** [comment]
Under the hood this library calls `getBytes` on your string. It uses the platform's default charset to encode the string, which may not be UTF-8. Could you try changing

```java
Notification notification = new Notification(subscription, "åäö"));
```

to

```java
import java.nio.charset.StandardCharsets;

...

Notification notification = new Notification(subscription.endpoint, subscription.keys.p256dh, subscription.keys.auth, "åäö".getBytes(StandardCharsets.UTF_8));
```

this would tell if the charset is the issue.

**Comment by martijndwars** [comment]
Just noticed there are [more](https://github.com/web-push-libs/webpush-java/blob/master/src/main/java/nl/martijndwars/webpush/HttpEce.java#L39-L42) occurrence sof `getBytes` without specific character encoding. I'll create a patch for this.
