### ISSUE TITLE
too slow when compared to javascript version

### ISSUE THREAD

**Issue by nikhil32** [web-push-libs/webpush-java#6]
Hi,

When I try to encrypt in node js it is taking around 1ms to complete where are here it is taking about
700+ ms on java version in the same machine.

**Comment by martijndwars** [comment]
Thanks for reporting this issue. The slowness is probably related to the cryptographic functions. Since these are part of third-party code (and possibly even related to Java primitives), optimising them becomes quite hard. Nevertheless, I'll look into it.

**Comment by xuwei-k** [comment]
I think the cause is `SecureRandom.getSeed`
- https://github.com/MartijnDwars/web-push/blob/4b27d73b44c8/src/main/java/nl/martijndwars/webpush/PushService.java#L68
- http://stackoverflow.com/q/137212

**Comment by martijndwars** [comment]
Hm.. sounds like we should factor out a `SaltProvider` such that you can plug in different implementation depending on your needs (RNG for highest security, PRNG for lesser security, or a constant for testing). I'll see what I can do.

**Comment by manindrMBK** [comment]
hey @MartijnDwars , did you find any fix for this? facing the same problem .it takes more than 30 seconds for encryption.

//code
  logger.info("encrypting data at "+System.currentTimeMillis());
 Encrypted encrypted = encrypt(
                notification.getPayload(),
                notification.getUserPublicKey(),
                notification.getUserAuth(),
                notification.getPadSize()
        );
 logger.info("encryption complete at "+System.currentTimeMillis());

//result

encrypting data at 1477463937489
encryption complete at 1477463976361

**Comment by martijndwars** [comment]
@manindr what operating system and JVM are you using? It would help if I can reproduce the problem (on my MacBook with Oracle's HotSpot 1.8 it runs in the order of seconds). Thanks in advance!

**Comment by manindrMBK** [comment]
CentOS 6.7 and java 8 on production
Ubuntu 15.10 and java 8 on local 
funny thing is on my local system, it tales around 800 ms whereas on production it takes 30 seconds.

**Comment by xuwei-k** [comment]
I think reproduce is too hard in local system. it depends on keyboard timings, mouse movements, etc
https://en.wikipedia.org/wiki/Entropy_(computing)

**Comment by manindrMBK** [comment]
oh, okay. So ,what can i do to fix this, guys? 

Thanks

**Comment by martijndwars** [comment]
I don't have a clear answer to that yet. This library uses `SecureRandom` to generate a 16-byte seed. SecureRandom [reads from](http://security.stackexchange.com/a/40634/27289) `/dev/urandom` and `/dev/urandom` [will never block](https://tersesystems.com/2015/12/17/the-right-way-to-use-securerandom/), so that raises the question why it takes 30 seconds to generate a 16-byte seed. According to [this](http://security.stackexchange.com/a/72906/27289) post, `SecureRandom` briefly uses `/dev/random` when generating a seed. If there is very little entropy on your server, it could take quite a while to perform this operation. Possible solutions:
- Install [haveged](http://stackoverflow.com/a/31208558/368220), a "random number generator that remedies low-entropy conditions in the Linux random device that can occur under some workloads, especially on headless servers." See also [this](https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged) tutorial.
- Change the source for random number generation in the JVM from `/dev/random` to `/dev/urandom`. [This](https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html) page offers some explanation.

Please let me know if any of these solutions work!

**Comment by hzr** [comment]
> Change the source for random number generation in the JVM from /dev/random to /dev/urandom.

I can confirm that this works. Thanks Martijn!

**Comment by hawlik** [comment]
> Install haveged, a "random number generator that remedies low-entropy conditions in the Linux random device that can occur under some workloads, especially on headless servers." See also this tutorial.

I can confirm that this work as well :)
I have installed haveged and stick with `/dev/random`. Now encryption tooks less then 10ms on average

Thanks Martijn,  really appreciate your effort!

**Comment by martijndwars** [comment]
Thanks for the feedback. I'll add a note to the README for future users and close this issue once that's done.

**Comment by mathikumar-c-3815** [comment]
@MartijnDwars I tried using SecureRandom.getSeed in my QA setup which is running on CentOS Linux and java 8.  As like everyone encryption takes above 10s. 

And I tried below code to generate securerandom as suggested by [link](https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom/) 

SecureRandom random = new SecureRandom();
        byte[] salt = new byte[16];
        random.nextBytes(salt); 

Now encryption takes  milliseconds only. 

Can you please check this and confirm.

Thanks in advance.

**Comment by martijndwars** [comment]
This was fixed 12 days ago in #41. The issue should not appear in the latest version (3.0.1). Are you using the latest version?

**Comment by mathikumar-c-3815** [comment]
Thanks for the quick update @MartijnDwars 
Sorry for not updating your library in our side. 
We are using older version.Will update it to 3.0.1.

Again Thanks a lot for excellent library for web push.
