### ISSUE TITLE
influence of deprecated  gcm 

### ISSUE THREAD

**Issue by titer1** [web-push-libs/webpush-java#85]
google will deprecated GCM at  May 29, 2019, 
so latest version of webpush-java  will be influenced ?
thank you !

[ref-link](https://developers.google.com/cloud-messaging/gcm)

**Comment by martijndwars** [comment]
Thanks for the heads-up. This should not be a problem, since Google's web-push implementation uses Firebase Cloud Messaging (FCM). Moreover, this library should be faithful to the web-push specification, which allows Google to switch between any web-push compatible service (FCM/GCM/...) without affecting this library.
